#!/bin/sh
#
# Usage:
#     git-get-desc path/to/repository
#
# Returns a string that identifies the version of the given repository
#




# Check if git is installed
git=`which git`
test -z "$git" && {
    echo "$0: Can't find git command! Aborting..." >&2
    exit 1
}


# Check if we are pointing to the right directory
cd "$1"
$git rev-parse --git-dir > /dev/null || {
    echo "$0: $1 is not a git repository! Aborting..." >&2
    exit 1
}
branch=`$git describe --exact-match 2> /dev/null`
test -z "$branch" &&
    branch=`$git rev-parse --abbrev-ref HEAD`
test "$branch" = HEAD &&
    branch=DETACHED
printf $branch-`$git rev-parse --short HEAD`
test -n "`$git status --porcelain -uno`" &&
    printf '*'
cd - > /dev/null

