/*******************************************************************************

    Version information generated at compile time.

    copyright:      Copyright (c) 2011 sociomantic labs. All rights reserved

    This file is automatically generated.

    DO NOT CHANGE, IT WILL BE OVERWRITTEN

    DO NOT ADD TO THE REPOSITORY

*******************************************************************************/

module @MODULE@;

import tango.core.Version: getVersionString;
import tango.transition;


istring[istring] Version;

static this()
{
    Version["version"] = "@VERSION@";
    Version["build_date"] = "@DATE@";
    Version["build_author"] = "@AUTHOR@";
    Version["compiler"] = "@COMPILER@";
    Version["lib_gc"] = "@GC@";
    Version["lib_tango"] = getVersionString();
@LIBRARIES@
}

// vim: set filetype=d :
